Fix timezone set if it fails

diff --git a/.github/workflows/immortalwrt-builder-self-host.yml b/.github/workflows/immortalwrt-builder-self-host.yml
--- a/.github/workflows/immortalwrt-builder-self-host.yml
+++ b/.github/workflows/immortalwrt-builder-self-host.yml
@@ -43,8 +43,8 @@ jobs:
         sudo apt-get -qq clean
     
     - name: Set timezone on the host
-      if: always()
-      run: sudo timedatectl set-timezone "$TZ"
+      if: 
+      run: sudo timedatectl set-timezone "$TZ" || echo "Failed to set timezone, proceeding anyway."
 
     - name: Authenticate GitHub
       env:
